# Generated by Django 6.0.4 on 2026-04-10 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical', '0001_initial'),
        ('users', '0002_remove_user_name_user_nom_user_prenom_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiermedical',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier', to='users.patient'),
        ),
    ]
