# Generated by Django 6.0.4 on 2026-04-12 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_initial'),
        ('users', '0005_patient_groupe_sanguin_user_failed_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiermedical',
            name='notes_medecin',
            field=models.TextField(blank=True, verbose_name='Notes du médecin'),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consult', models.DateTimeField()),
                ('diagnostic', models.TextField(blank=True)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='medical.dossiermedical')),
                ('medecin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.medecin')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament', models.CharField(max_length=200)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('posologie', models.CharField(blank=True, max_length=200)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='medical.dossiermedical')),
                ('medecin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.medecin')),
            ],
        ),
        migrations.CreateModel(
            name='ResultatAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examen', models.CharField(max_length=200)),
                ('valeur', models.CharField(blank=True, max_length=100)),
                ('unite', models.CharField(blank=True, max_length=50)),
                ('norme', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(blank=True, max_length=20)),
                ('date_examen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_labo', to='medical.dossiermedical')),
            ],
        ),
    ]
