# Generated by Django 6.0.4 on 2026-04-16 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_dossiermedical_notes_medecin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignesVitaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids', models.FloatField(blank=True, null=True, verbose_name='Poids (kg)')),
                ('taille', models.IntegerField(blank=True, null=True, verbose_name='Taille (cm)')),
                ('tension_systolique', models.IntegerField(blank=True, null=True, verbose_name='Tension Systolique')),
                ('tension_diastolique', models.IntegerField(blank=True, null=True, verbose_name='Tension Diastolique')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='Température (°C)')),
                ('frequence_cardiaque', models.IntegerField(blank=True, null=True, verbose_name='Fréquence Cardiaque (bpm)')),
                ('saturation_oxygene', models.IntegerField(blank=True, null=True, verbose_name='Saturation O2 (%)')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signes_vitaux', to='medical.dossiermedical')),
                ('infirmier', models.ForeignKey(limit_choices_to={'role': 'INFIRMIER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
