# Generated by Django 6.0.4 on 2026-04-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='duree',
            field=models.IntegerField(default=30, verbose_name='Durée en minutes'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
    ]
