# Generated by Django 6.0.4 on 2026-04-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_name_user_nom_user_prenom_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='statut',
            field=models.BooleanField(default=False),
        ),
    ]
