# Generated by Django 6.0.4 on 2026-04-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_patient_groupe_sanguin_user_failed_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='poids',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='taille',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
