# Generated by Django 6.0.4 on 2026-04-12 17:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_patient_poids_patient_taille'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_specifique', models.DateField(default=django.utils.timezone.now)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='users.medecin')),
            ],
            options={
                'ordering': ['date_specifique'],
                'unique_together': {('medecin', 'date_specifique')},
            },
        ),
    ]
