# Generated by Django 6.0.4 on 2026-04-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_disponibilite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PATIENT', 'Patient'), ('MEDECIN', 'Médecin'), ('INFIRMIER', 'Infirmier'), ('ADMIN', 'Administrateur')], default='PATIENT', max_length=15),
        ),
    ]
